-- BH

create table "public"."short_links" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "name" text,
    "alias" text not null default substr(md5((random())::text), 1, 6),
    "long_link" text not null,
    "user_id" integer not null
);


alter table "public"."short_links" enable row level security;

CREATE UNIQUE INDEX short_links_alias_key ON public.short_links USING btree (alias);

CREATE UNIQUE INDEX short_links_pkey ON public.short_links USING btree (id);

alter table "public"."short_links" add constraint "short_links_pkey" PRIMARY KEY using index "short_links_pkey";

alter table "public"."short_links" add constraint "short_links_alias_key" UNIQUE using index "short_links_alias_key";

alter table "public"."short_links" add constraint "short_links_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."short_links" validate constraint "short_links_user_id_fkey";

grant delete on table "public"."short_links" to "anon";

grant insert on table "public"."short_links" to "anon";

grant references on table "public"."short_links" to "anon";

grant select on table "public"."short_links" to "anon";

grant trigger on table "public"."short_links" to "anon";

grant truncate on table "public"."short_links" to "anon";

grant update on table "public"."short_links" to "anon";

grant delete on table "public"."short_links" to "authenticated";

grant insert on table "public"."short_links" to "authenticated";

grant references on table "public"."short_links" to "authenticated";

grant select on table "public"."short_links" to "authenticated";

grant trigger on table "public"."short_links" to "authenticated";

grant truncate on table "public"."short_links" to "authenticated";

grant update on table "public"."short_links" to "authenticated";

grant delete on table "public"."short_links" to "service_role";

grant insert on table "public"."short_links" to "service_role";

grant references on table "public"."short_links" to "service_role";

grant select on table "public"."short_links" to "service_role";

grant trigger on table "public"."short_links" to "service_role";

grant truncate on table "public"."short_links" to "service_role";

grant update on table "public"."short_links" to "service_role";